#name: lluchmk.Cache.Core NuGet pacakge
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

# Run on commits on master branch
trigger:
  - master
  - yaml_pipeline

variables:
  buildConfiguration: Release

jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: set
    displayName: 'Show variables'

  - script: dotnet restore
    displayName: 'Restore packages'

  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build $(buildConfiguration)'

#  - task: DotNetCoreCLI@2
#    displayName: 'Test'
#    inputs:
#      command: test
#      projects: '**/*Tests/*.csproj'
#      arguments: '--configuration $(buildConfiguration)'
#      publishTestResults: true 

  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: pack
      packagesToPack: 'Cache.Core/Cache.Core.csproj'
      #versioningScheme: byPrereleaseNumber
      #majorVersion: '0'
      #minorVersion: '1'
      #patchVersion: '0'
      #packTimezone: 'utc'
      versioningScheme: byBuildNumber

  - task: PublishBuildArtifacts@1
    displayName: 'Store artifact'
    condition: succeeded()
    # If allowing more than one branch we could publish or deploy to different feeds
    #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      artifactname: 'NuGetPackage'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
  - powershell: |
      echo "##vso[task.setvariable variable=notificationBody;isOutput=true]New build on $env:SYSTEM_TEAMPROJECT: $env:BUILD_BUILDNUMBER.
      Status: $env:AGENT_JOBSTATUS
      <$env:SYSTEM_COLLECTIONURI/$env:SYSTEM_TEAMPROJECT/_build/results?buildId=$env:BUILD_BUILDID&view=logs|Details>"
    name: setMessage

  # Moved to a release pipeline
  #- task: NuGetCommand@2
  #  displayName: 'Push to NuGet.org'
  #  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  #  inputs:
  #    command: push
  #    nugetFeedType: external
  #    publishFeedCredentials: 'NuGetOrg'
  #    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'

- job: Notify
  dependsOn: Build
  #condition: succeeded()
  pool: server
  variables:
    teamProject: $(SYSTEM_TEAMPROJECT)
    buildNumber: $(BUILD_BUILDNUMBER)
    jobStatus: $(AGENT_JOBSTATUS)
    collectionUri: $(SYSTEM_COLLECTIONURI)
    buildId: $(BUILD_BUILDID)
    message: |
      {
        "text": $[ dependencies.Build.outputs['setMessage.notificationBody'] ]
      }
    mySimpleVar: simple var value
    "my.dotted.var": dotted var value
    "my var with spaces": var with spaces value
    longvar: |
      asdasfeesacsdas
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: connectedServiceName
      serviceConnection: SlackWebHook
      method: POST
      body: $(message)