#name: lluchmk.Cache.Core NuGet pacakge
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

# Run on commits on master branch
trigger:
  - master

variables:
  buildConfiguration: Release

pool:
  vmImage: 'vs2017-win2016'

steps:

- script: set
  displayName: 'Show variables'

- script: dotnet restore
  displayName: 'Restore packages'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true 

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: pack
    packagesToPack: 'Cache.Core/Cache.Core.csproj'
    #versioningScheme: byPrereleaseNumber
    #majorVersion: '0'
    #minorVersion: '1'
    #patchVersion: '0'
    #packTimezone: 'utc'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: 'Push to NuGet.org'
  condition: and(succeedd(), eq(variables['Build.SourceBranchName'], 'master'))
  inputs:
    command: push
    nugetFeedType: external
    publishFeedCredentials: 'NuGetOrg'
    packagesToPus: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'