name: lluchmk.Cache.Core NuGet pacakge

# Run on commits on master branch
trigger:
    - master

variables:
    buildConfiguration: Release

pool:
    vmImage: 'Ubuntu 16.04'

steps:

- script: set
    displayName: 'Show variables'

- script: dotnet restore
    displayName: 'Restore packages'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
        command: Test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

- task: NuGet@2
    displayName: 'Pack'
    inputs:
        command: pack
        packagesToPack: 'Cache.Core/Cache.Core.csproj'
        versioningScheme: byBuildNumber
        includeSymbols: true